version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: greenbiller_php
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: greenbiller_nginx
    ports:
      - "3060:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: greenbiller_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: greenbiller_db
      MYSQL_USER: greenbiller_user
      MYSQL_PASSWORD: greenbiller_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
